import ajustador as aju

def params_fitness(morph_file,ntype,modeltype,ghkkluge):

    P = aju.optimize.AjuParam
    params = aju.optimize.ParamSet(
        P('junction_potential', 0, fixed=1),
        P('RA',                 5.3,  min=1,      max=200),
        P('RM',                2.78,   min=0.1,      max=10),
        P('CM',                 0.010, min=0.001,      max=0.03),
        P('Cond_Kir',      9.5,      min=0, max=20),
        P('Eleak', -0.08, min=-0.080, max=-0.030),
        P('Cond_NaF_0',      219e3,      min=0, max=600e3),
        P('Cond_KaS_0',      599,        min=0, max=2000),
        P('Cond_KaF_0',      887,        min=0, max=2000),
        P('Cond_Krp_0',      0.05,        min=0, max=60),
        P('Cond_CaCC_0',      0.5,        min=0, max=60),
        P('Cond_SKCa', 1.7, min=0, max=10),
        P('Cond_BKCa', 5.6, min=0, max=50),
        P('Cond_CaN_0',      3*ghkkluge,      min=0, max=100*ghkkluge),
        P('Cond_CaL12_0',    8*ghkkluge,      min=0, max=100*ghkkluge),
        P('Cond_CaL13_0',   12*ghkkluge,      min=0, max=100*ghkkluge),
        P('Cond_CaR_0',     20*ghkkluge,      min=0, max=1000*ghkkluge),
        P('Chan_NaF_vshift_X', 0.0, min=-0.01, max=0.01),
        P('Chan_NaF_vshift_Y', 0.0, min=-0.01, max=0.01),
        P('Chan_NaF_taumul_X', 1.0, min=0.5, max=2),
        P('Chan_NaF_taumul_Y', 1.0, min=0.5, max=2),
        P('Chan_KaS_vshift_X', 0.0, min=-0.01, max=0.01),
        P('Chan_KaS_vshift_Y', 0.0, min=-0.01, max=0.01),
        P('Chan_KaS_taumul_X', 1.0, min=0.6, max=1.8),
        P('Chan_KaS_taumul_Y', 1.0, min=0.6, max=1.8),
        P('Chan_KaF_vshift_X', 0.0, min=-0.01, max=0.01),
        P('Chan_KaF_vshift_Y', 0.0, min=-0.01, max=0.01),
        P('Chan_KaF_taumul_X', 1.0, min=0.6, max=1.8),
        P('Chan_KaF_taumul_Y', 1.0, min=0.6, max=1.8),
        P('Chan_Krp_vshift_X', 0.0, min=-0.01, max=0.01),
        P('Chan_Krp_taumul_X', 1.0, min=0.6, max=1.8),
        P('Chan_CaL12_vshift_X', 0.0, min=-0.01, max=0.01),
        P('Chan_CaL12_vshift_Y', 0.0, min=-0.01, max=0.01),
        P('Chan_CaL12_taumul_X', 1.0, min=0.6, max=1.8),
        P('Chan_CaL12_taumul_Y', 1.0, min=0.6, max=1.8),
        P('Chan_CaL13_vshift_X', 0.0, min=-0.01, max=0.01),
        P('Chan_CaL13_vshift_Y', 0.0, min=-0.01, max=0.01),
        P('Chan_CaL13_taumul_X', 1.0, min=0.6, max=1.8),
        P('Chan_CaL13_taumul_Y', 1.0, min=0.6, max=1.8),
        P('Chan_CaR_vshift_X', 0.0, min=-0.01, max=0.01),
        P('Chan_CaR_vshift_Y', 0.0, min=-0.01, max=0.01),
        P('Chan_CaR_taumul_X', 1.0, min=0.6, max=1.8),
        P('Chan_CaR_taumul_Y', 1.0, min=0.6, max=1.8),
        P('Chan_CaN_vshift_X', 0.0, min=-0.01, max=0.01),
        P('Chan_CaN_vshift_Y', 0.0, min=-0.01, max=0.01),
        P('Chan_CaN_taumul_X', 1.0, min=0.6, max=1.8),
        P('Chan_CaN_taumul_Y', 1.0, min=0.6, max=1.8),
        P('Chan_CaCC_taumul', 1.0, min=0.5, max=2),
        P('morph_file', morph_file, fixed=1),
        P('neuron_type', ntype,                     fixed=1),
        P('model',           modeltype,     fixed=1))

    #fitness=aju.fitnesses.combined_fitness('new_combined_fitness')
    fitness = aju.fitnesses.combined_fitness('empty',
                                             response=3,
                                             baseline_pre=2,
                                             baseline_post=2,
                                             rectification=1,
                                             falling_curve_time=1,
                                             spike_time=3,
                                             spike_width=2,
                                             spike_height=4,
                                             spike_latency=2,
                                             spike_count=3,
                                             spike_ahp=1,
                                             ahp_curve=2,
                                             mean_isi=2,
                                             isi_spread=2,
                                             #post_injection_curve_tau=2,
                                             #charging_curve_time=1,
                                             charging_curve_full=2,
                                             spike_range_y_histogram=1)
    return params,fitness
